# Generated by Django 5.2.6 on 2025-10-08 10:02

import core.infrastructure.models.sql_models
import core.infrastructure.repositories.sql_repos_helper
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.TextField(blank=True, null=True)),
                ("type", models.CharField(max_length=255)),
                ("see_also", models.CharField(max_length=255)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "data_types",
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("author_id", models.CharField(max_length=255, null=True)),
                ("given_name", models.CharField(max_length=255)),
                ("family_name", models.CharField(max_length=255)),
                ("name", models.TextField(blank=True, null=True)),
                ("orcid", models.CharField(blank=True, max_length=50, null=True)),
                ("json", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "authors",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("book_id", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("date_published", models.TextField(blank=True, null=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
            ],
            options={
                "db_table": "books",
            },
        ),
        migrations.CreateModel(
            name="DataItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.TextField(blank=True, null=True)),
                ("source_url", models.TextField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("article_id", models.TextField(blank=True, null=True)),
                ("source_table", models.JSONField(blank=True, null=True)),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=core.infrastructure.models.sql_models.OverwriteStorage(),
                        upload_to=core.infrastructure.models.sql_models.dataitem_source_file_upload_path,
                    ),
                ),
            ],
            options={
                "db_table": "data_items",
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("dataset_id", models.CharField(max_length=255, null=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_published", models.DateTimeField(blank=True, null=True)),
                ("identifier", models.CharField(max_length=255, null=True)),
                ("json", models.JSONField(blank=True, null=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
            ],
            options={
                "db_table": "datasets",
            },
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mean", models.TextField(blank=True, null=True)),
                ("standard_deviation", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClassDiscovery",
            fields=[
                (
                    "datatype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="infrastructure.datatype",
                    ),
                ),
                ("class_discovery_label", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "class_discoveries",
            },
            bases=("infrastructure.datatype",),
        ),
        migrations.CreateModel(
            name="CorrelationAnalysis",
            fields=[
                (
                    "datatype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="infrastructure.datatype",
                    ),
                ),
                ("correlation_analysis_label", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "correlation_analysis",
            },
            bases=("infrastructure.datatype",),
        ),
        migrations.CreateModel(
            name="DataPreprocessing",
            fields=[
                (
                    "datatype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="infrastructure.datatype",
                    ),
                ),
                ("data_preprocessing_label", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "data_preprocessing",
            },
            bases=("infrastructure.datatype",),
        ),
        migrations.CreateModel(
            name="DescriptiveStatistics",
            fields=[
                (
                    "datatype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="infrastructure.datatype",
                    ),
                ),
                ("descriptive_statistics_label", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "descriptive_statistics",
            },
            bases=("infrastructure.datatype",),
        ),
        migrations.CreateModel(
            name="FactorAnalysis",
            fields=[
                (
                    "datatype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="infrastructure.datatype",
                    ),
                ),
                ("factor_analysis_label", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "factor_analysis",
            },
            bases=("infrastructure.datatype",),
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("chapter_id", models.CharField(max_length=255, null=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("page_end", models.CharField(max_length=255, null=True)),
                ("page_start", models.CharField(max_length=255, null=True)),
                ("json", models.JSONField(blank=True, null=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "is_part_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="infrastructure.book",
                    ),
                ),
            ],
            options={
                "db_table": "chapters",
            },
        ),
        migrations.CreateModel(
            name="ChapterAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infrastructure.author",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infrastructure.chapter",
                    ),
                ),
            ],
            options={
                "db_table": "chapter_authors",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="chapters",
                through="infrastructure.ChapterAuthor",
                to="infrastructure.author",
            ),
        ),
        migrations.CreateModel(
            name="Concept",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("concept_id", models.CharField(max_length=255, null=True)),
                ("json", models.JSONField(blank=True, null=True)),
                ("label", models.CharField(max_length=255)),
                ("definition", models.TextField(blank=True, null=True)),
                (
                    "string_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("see_also", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "concepts",
                "indexes": [
                    models.Index(fields=["label"], name="concepts_label_dfa803_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Constraint",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("_id", models.CharField(max_length=255, null=True, unique=True)),
                ("json", models.JSONField(blank=True, null=True)),
                ("label", models.CharField(max_length=255, null=True, unique=True)),
                (
                    "exact_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "close_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "constraints",
                "indexes": [
                    models.Index(fields=["_id"], name="constraints__id_b2bf28_idx"),
                    models.Index(fields=["label"], name="constraints_label_bdf51b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("contribution_paper_id", models.CharField(max_length=255)),
                ("json_id", models.TextField(blank=True, null=True)),
                ("json_type", models.TextField(blank=True, null=True)),
                ("json_context", models.JSONField(blank=True, null=True)),
                ("label", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("author", models.JSONField(blank=True, null=True)),
                ("info", models.JSONField(blank=True, null=True)),
                ("predicates", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "contributions",
                "indexes": [
                    models.Index(
                        fields=["contribution_paper_id"],
                        name="contributio_contrib_b46a03_idx",
                    ),
                    models.Index(
                        fields=["json_id"], name="contributio_json_id_bb89bd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CreativeWork",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("creative_work_id", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("identifier", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "creative_works",
                "indexes": [
                    models.Index(fields=["name"], name="creative_wo_name_b3cf1f_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="datatype",
            name="has_inputs",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="input_data",
                to="infrastructure.dataitem",
            ),
        ),
        migrations.AddField(
            model_name="datatype",
            name="has_outputs",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="output_data",
                to="infrastructure.dataitem",
            ),
        ),
        migrations.CreateModel(
            name="DataItemComponent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.TextField(blank=True, null=True)),
                ("see_also", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "data_item_components",
                "indexes": [
                    models.Index(fields=["id"], name="data_item_c_id_8e5395_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="dataitem",
            name="has_part",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="data_item",
                to="infrastructure.dataitemcomponent",
            ),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_published", models.DateTimeField(blank=True, null=True)),
                (
                    "has_part",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "is_based_on",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("status", models.CharField(max_length=255, null=True)),
                (
                    "ro_crate",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=core.infrastructure.models.sql_models.OverwriteStorage(),
                        upload_to=core.infrastructure.repositories.sql_repos_helper.articlet_ro_crate_upload_path,
                    ),
                ),
                ("article_id", models.CharField(max_length=255, null=True)),
                ("json", models.JSONField(blank=True, null=True)),
                ("reborn_doi", models.TextField(blank=True, null=True)),
                (
                    "research_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        help_text="High-level tags like ['dataset','scholarly_article', 'chapter']",
                        size=None,
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "related_chapters",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Chapters related to this article",
                        related_name="articles",
                        to="infrastructure.chapter",
                    ),
                ),
                (
                    "concepts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="digital_objects",
                        to="infrastructure.concept",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        db_column="license",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_objects",
                        to="infrastructure.creativework",
                    ),
                ),
                (
                    "related_datasets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Datasets related to this article",
                        related_name="articles",
                        to="infrastructure.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "digital_objects",
            },
        ),
        migrations.CreateModel(
            name="DatasetAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infrastructure.author",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infrastructure.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "dataset_authors",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="dataset",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="datasets",
                through="infrastructure.DatasetAuthor",
                to="infrastructure.author",
            ),
        ),
        migrations.CreateModel(
            name="DigitalObjectAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infrastructure.article",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infrastructure.author",
                    ),
                ),
            ],
            options={
                "db_table": "digital_objects_authors",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="digital_objects",
                through="infrastructure.DigitalObjectAuthor",
                to="infrastructure.author",
            ),
        ),
        migrations.CreateModel(
            name="Figure",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.TextField(blank=True, null=True)),
                ("source_url", models.TextField(blank=True, null=True)),
                (
                    "source_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=core.infrastructure.models.sql_models.OverwriteStorage(),
                        upload_to=core.infrastructure.models.sql_models.figure_source_image_upload_path_alternative,
                    ),
                ),
                ("article_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "figures",
                "indexes": [models.Index(fields=["id"], name="figures_id_a5d216_idx")],
            },
        ),
        migrations.AddField(
            model_name="dataitem",
            name="has_expression",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="data_item",
                to="infrastructure.figure",
            ),
        ),
        migrations.CreateModel(
            name="Identifier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("_id", models.CharField(max_length=255, null=True)),
                ("identifier_value", models.CharField(max_length=255)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("research_field", "ResearchField"),
                            ("author", "Author"),
                            ("publisher", "Publisher"),
                            ("journal_conference", "JournalConference"),
                            ("article", "Article"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("uuid", "UUID"),
                            ("external_id", "External ID"),
                            ("doi", "DOI"),
                        ],
                        default="doi",
                        max_length=50,
                    ),
                ),
                ("entity_id", models.PositiveBigIntegerField()),
            ],
            options={
                "verbose_name": "Identifier",
                "verbose_name_plural": "Identifiers",
                "db_table": "identifiers",
                "indexes": [
                    models.Index(fields=["_id"], name="identifiers__id_6cc599_idx"),
                    models.Index(
                        fields=["identifier_value"],
                        name="identifiers_identif_4e207f_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="identifiers_entity__3398d3_idx",
                    ),
                ],
                "unique_together": {("entity_type", "entity_id", "identifier_type")},
            },
        ),
        migrations.CreateModel(
            name="JournalConference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("_id", models.CharField(max_length=255, null=True)),
                ("journal_conference_id", models.CharField(max_length=255, null=True)),
                ("json", models.JSONField(blank=True, null=True)),
                ("label", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "journals_conferences",
                "indexes": [
                    models.Index(fields=["_id"], name="journals_co__id_98caea_idx"),
                    models.Index(fields=["label"], name="journals_co_label_b97d00_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MartixSize",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("number_rows", models.TextField(blank=True, null=True)),
                ("number_columns", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "martix_sizes",
                "indexes": [
                    models.Index(fields=["id"], name="martix_size_id_285427_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="dataitem",
            name="has_characteristic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_item",
                to="infrastructure.martixsize",
            ),
        ),
        migrations.CreateModel(
            name="Matrix",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("_id", models.CharField(max_length=255, null=True, unique=True)),
                ("json", models.JSONField(blank=True, null=True)),
                ("label", models.CharField(max_length=255, null=True, unique=True)),
                (
                    "type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "exact_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "close_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "matrices",
                "indexes": [
                    models.Index(fields=["_id"], name="matrices__id_eb1d71_idx"),
                    models.Index(fields=["label"], name="matrices_label_854779_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ObjectOfInterest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("json", models.JSONField(blank=True, null=True)),
                ("label", models.CharField(max_length=255, null=True, unique=True)),
                (
                    "type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "exact_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "close_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "object_of_interests",
                "indexes": [
                    models.Index(fields=["label"], name="object_of_i_label_c3467d_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("_id", models.CharField(max_length=255, null=True, unique=True)),
                ("json", models.JSONField(blank=True, null=True)),
                ("label", models.CharField(max_length=255, null=True, unique=True)),
                (
                    "exact_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "close_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "operations",
                "indexes": [
                    models.Index(fields=["_id"], name="operations__id_27a070_idx"),
                    models.Index(fields=["label"], name="operations_label_8f11d6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("organization_id", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("url", models.TextField(blank=True, null=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
            ],
            options={
                "db_table": "organizations",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="organizatio_search__1aa910_gin"
                    ),
                    models.Index(fields=["name"], name="organizatio_name_5cd1d4_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="dataset",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datasets",
                to="infrastructure.organization",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="infrastructure.organization",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="affiliation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors",
                to="infrastructure.organization",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                db_column="publisher",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="digital_objects",
                to="infrastructure.organization",
            ),
        ),
        migrations.CreateModel(
            name="Periodical",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("periodical_id", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_issues",
                        to="infrastructure.organization",
                    ),
                ),
            ],
            options={
                "db_table": "periodicals",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("json", models.JSONField(blank=True, null=True)),
                ("label", models.CharField(max_length=255, null=True, unique=True)),
                (
                    "exact_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "close_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "properties",
                "indexes": [
                    models.Index(fields=["label"], name="properties_label_6b6498_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("_id", models.CharField(max_length=255, null=True, unique=True)),
                ("label", models.CharField(max_length=255, null=True)),
                ("json", models.JSONField(blank=True, null=True)),
                (
                    "string_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "exact_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "close_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "matrices",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="components",
                        to="infrastructure.matrix",
                    ),
                ),
                (
                    "object_of_interests",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="components",
                        to="infrastructure.objectofinterest",
                    ),
                ),
                (
                    "operations",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="components",
                        to="infrastructure.operation",
                    ),
                ),
                (
                    "properties",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="components",
                        to="infrastructure.property",
                    ),
                ),
            ],
            options={
                "db_table": "components",
            },
        ),
        migrations.CreateModel(
            name="PublicationIssue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("publication_issue_id", models.TextField(blank=True, null=True)),
                ("date_published", models.TextField(blank=True, null=True)),
                (
                    "is_part_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_issues",
                        to="infrastructure.periodical",
                    ),
                ),
            ],
            options={
                "db_table": "publication_issues",
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("_id", models.CharField(max_length=255, null=True)),
                ("publisher_id", models.CharField(max_length=255, null=True)),
                ("json", models.JSONField(blank=True, null=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "publishers",
                "indexes": [
                    models.Index(fields=["_id"], name="publishers__id_9a496d_idx"),
                    models.Index(fields=["label"], name="publishers_label_37c529_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ResearchField",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("research_field_id", models.CharField(max_length=255, null=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "research_fields",
                "indexes": [
                    models.Index(fields=["label"], name="research_fi_label_234300_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="research_fields",
            field=models.ManyToManyField(
                blank=True,
                db_table="digital_objects_research_fields",
                related_name="digital_objects",
                to="infrastructure.researchfield",
            ),
        ),
        migrations.CreateModel(
            name="SchemaType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type_id", models.CharField(max_length=255, unique=True)),
                ("schema_data", models.JSONField()),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "property",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "schemata",
                "indexes": [
                    models.Index(
                        fields=["type_id"], name="schemata_type_id_be3b12_idx"
                    ),
                    models.Index(
                        fields=["last_updated"], name="schemata_last_up_e826b6_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="datatype",
            name="schema_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_type",
                to="infrastructure.schematype",
            ),
        ),
        migrations.CreateModel(
            name="ScholarlyArticle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("scholarly_article_id", models.CharField(max_length=255, null=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("json", models.JSONField(blank=True, null=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "is_part_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarly_articles",
                        to="infrastructure.publicationissue",
                    ),
                ),
            ],
            options={
                "db_table": "scholarly_articles",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="related_scholarly_articles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Scholarly articles related to this article",
                related_name="articles",
                to="infrastructure.scholarlyarticle",
            ),
        ),
        migrations.CreateModel(
            name="ScholarlyArticleAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infrastructure.scholarlyarticle",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infrastructure.author",
                    ),
                ),
            ],
            options={
                "db_table": "scholarly_article_authors",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="scholarlyarticle",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="scholarly_articles",
                through="infrastructure.ScholarlyArticleAuthor",
                to="infrastructure.author",
            ),
        ),
        migrations.CreateModel(
            name="SeeAlso",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("_id", models.CharField(max_length=255, null=True, unique=True)),
                ("label", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "see_alsos",
                "indexes": [
                    models.Index(fields=["_id"], name="see_alsos__id_d4758d_idx"),
                    models.Index(fields=["label"], name="see_alsos_label_dd8e3a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SharedType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                (
                    "see_also",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "shared_types",
                "indexes": [
                    models.Index(fields=["id"], name="shared_type_id_05b5fe_idx"),
                    models.Index(fields=["label"], name="shared_type_label_8e78f5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Software",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.TextField(blank=True, null=True)),
                ("version_info", models.TextField(blank=True, null=True)),
                ("has_support_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "softwares",
                "indexes": [
                    models.Index(fields=["id"], name="softwares_id_be8100_idx"),
                    models.Index(fields=["label"], name="softwares_label_d1d359_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SoftwareLibrary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.TextField(blank=True, null=True)),
                ("version_info", models.TextField(blank=True, null=True)),
                (
                    "has_support_url",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "part_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_of_software",
                        to="infrastructure.software",
                    ),
                ),
            ],
            options={
                "db_table": "software_libraries",
            },
        ),
        migrations.CreateModel(
            name="SoftwareMethod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.TextField(blank=True, null=True)),
                (
                    "is_implemented_by",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, null=True),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "has_support_url",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "part_of",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="software_methods",
                        to="infrastructure.softwarelibrary",
                    ),
                ),
            ],
            options={
                "db_table": "software_methods",
            },
        ),
        migrations.AddField(
            model_name="datatype",
            name="executes",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="software_method",
                to="infrastructure.softwaremethod",
            ),
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("_id", models.CharField(max_length=255, null=True)),
                ("statement_id", models.CharField(max_length=255, null=True)),
                ("json", models.JSONField(blank=True, null=True)),
                ("content", models.JSONField(blank=True, null=True)),
                ("version", models.CharField(max_length=255, null=True)),
                ("encodingFormat", models.CharField(max_length=255, null=True)),
                ("name", models.CharField(blank=True, null=True)),
                (
                    "json_ld",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=core.infrastructure.models.sql_models.OverwriteStorage(),
                        upload_to="json_ld_files/",
                    ),
                ),
                ("label", models.CharField(blank=True, null=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="infrastructure.article",
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="statements",
                        to="infrastructure.author",
                    ),
                ),
                (
                    "components",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="statements",
                        to="infrastructure.component",
                    ),
                ),
                (
                    "concepts",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="statements",
                        to="infrastructure.concept",
                    ),
                ),
            ],
            options={
                "db_table": "statements",
            },
        ),
        migrations.CreateModel(
            name="Implement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.TextField(blank=True, null=True)),
                ("article_id", models.CharField(max_length=255, null=True)),
                (
                    "source_code",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=core.infrastructure.models.sql_models.OverwriteStorage(),
                        upload_to=core.infrastructure.models.sql_models.implement_source_code_upload_path,
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="implement_statements",
                        to="infrastructure.statement",
                    ),
                ),
            ],
            options={
                "db_table": "implements",
            },
        ),
        migrations.CreateModel(
            name="HasPart",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "schema_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="has_parts",
                        to="infrastructure.schematype",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="has_part_statements",
                        to="infrastructure.statement",
                    ),
                ),
            ],
            options={
                "db_table": "has_parts",
            },
        ),
        migrations.AddField(
            model_name="datatype",
            name="statement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_type_statement",
                to="infrastructure.statement",
            ),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("unit_id", models.CharField(max_length=255, null=True, unique=True)),
                ("label", models.TextField(blank=True, null=True)),
                ("json", models.JSONField(blank=True, null=True)),
                (
                    "type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "exact_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "close_match",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "units",
                "indexes": [
                    models.Index(fields=["label"], name="units_label_2e6f3b_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="component",
            name="units",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="components",
                to="infrastructure.unit",
            ),
        ),
        migrations.CreateModel(
            name="AlgorithmEvaluation",
            fields=[
                (
                    "datatype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="infrastructure.datatype",
                    ),
                ),
                (
                    "evaluate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluate",
                        to="infrastructure.sharedtype",
                    ),
                ),
                (
                    "evaluates_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluates_for",
                        to="infrastructure.sharedtype",
                    ),
                ),
            ],
            options={
                "db_table": "algorithm_evaluations",
            },
            bases=("infrastructure.datatype",),
        ),
        migrations.CreateModel(
            name="ClassPrediction",
            fields=[
                (
                    "datatype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="infrastructure.datatype",
                    ),
                ),
                (
                    "targets",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="class_predictions",
                        to="infrastructure.sharedtype",
                    ),
                ),
            ],
            options={
                "db_table": "class_predictions",
            },
            bases=("infrastructure.datatype",),
        ),
        migrations.CreateModel(
            name="GroupComparison",
            fields=[
                (
                    "datatype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="infrastructure.datatype",
                    ),
                ),
                (
                    "targets",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="group_comparisons",
                        to="infrastructure.sharedtype",
                    ),
                ),
            ],
            options={
                "db_table": "group_comparisons",
            },
            bases=("infrastructure.datatype",),
        ),
        migrations.CreateModel(
            name="MultilevelAnalysis",
            fields=[
                (
                    "datatype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="infrastructure.datatype",
                    ),
                ),
                (
                    "level",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="level_multilevel_analysis",
                        to="infrastructure.sharedtype",
                    ),
                ),
                (
                    "targets",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="targets_multilevel_analysis",
                        to="infrastructure.sharedtype",
                    ),
                ),
            ],
            options={
                "db_table": "multilevel_analysis",
            },
            bases=("infrastructure.datatype",),
        ),
        migrations.CreateModel(
            name="RegressionAnalysis",
            fields=[
                (
                    "datatype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="infrastructure.datatype",
                    ),
                ),
                (
                    "targets",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="regression_analysis",
                        to="infrastructure.sharedtype",
                    ),
                ),
            ],
            options={
                "db_table": "regression_analysis",
            },
            bases=("infrastructure.datatype",),
        ),
        migrations.AddIndex(
            model_name="dataitem",
            index=models.Index(fields=["id"], name="data_items_id_28ce59_idx"),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(
                fields=["description"], name="datasets_descrip_f0e088_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["name"], name="books_name_fa281b_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["author_id"], name="authors_author__7cfac6_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["name"], name="authors_name_e12c66_idx"),
        ),
        migrations.AddIndex(
            model_name="periodical",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="periodicals_search__adea27_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="periodical",
            index=models.Index(fields=["name"], name="periodicals_name_709802_idx"),
        ),
        migrations.AddIndex(
            model_name="publicationissue",
            index=models.Index(
                fields=["date_published"], name="publication_date_pu_766050_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="digital_obj_search__602175_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["name"], name="digital_obj_name_9fa0e9_idx"),
        ),
        migrations.AddIndex(
            model_name="softwarelibrary",
            index=models.Index(fields=["id"], name="software_li_id_bd34bf_idx"),
        ),
        migrations.AddIndex(
            model_name="softwarelibrary",
            index=models.Index(fields=["label"], name="software_li_label_7158e2_idx"),
        ),
        migrations.AddIndex(
            model_name="softwaremethod",
            index=models.Index(fields=["id"], name="software_me_id_337365_idx"),
        ),
        migrations.AddIndex(
            model_name="softwaremethod",
            index=models.Index(fields=["label"], name="software_me_label_d7a52e_idx"),
        ),
        migrations.AddIndex(
            model_name="statement",
            index=models.Index(fields=["_id"], name="statements__id_36075c_idx"),
        ),
        migrations.AddIndex(
            model_name="statement",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="statements_search__3e5a6d_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="implement",
            index=models.Index(fields=["id"], name="implements_id_103e48_idx"),
        ),
        migrations.AddIndex(
            model_name="haspart",
            index=models.Index(fields=["id"], name="has_parts_id_176cdd_idx"),
        ),
        migrations.AddIndex(
            model_name="datatype",
            index=models.Index(fields=["id"], name="data_types_id_0a4474_idx"),
        ),
        migrations.AddIndex(
            model_name="datatype",
            index=models.Index(fields=["label"], name="data_types_label_7f33d1_idx"),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(fields=["_id"], name="components__id_aa537f_idx"),
        ),
    ]
