# Generated by Django 5.1.9 on 2025-08-15 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataitem",
            name="statement",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct reference to Statement for efficient file path organization. Automatically populated from DataType relationships when not set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataitem_statements",
                to="infrastructure.statement",
            ),
        ),
    ]
