# Generated by Django 5.1.9 on 2025-09-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="research_fields",
            field=models.ManyToManyField(
                blank=True,
                db_table="digital_objects_research_fields",
                related_name="digital_objects",
                to="infrastructure.researchfield",
            ),
        ),
    ]
