# Generated by Django 5.1.9 on 2025-07-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="operations",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="components",
                to="infrastructure.operation",
            ),
        ),
    ]
