# Generated by Django 5.1.9 on 2025-06-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datatype",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
    ]
