# Generated by Django 5.2.6 on 2025-09-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="property",
            name="properties__id_5965b6_idx",
        ),
        migrations.RemoveField(
            model_name="property",
            name="_id",
        ),
        migrations.AlterField(
            model_name="property",
            name="label",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
