# Generated by Django 5.1.9 on 2025-07-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0002_component_operations"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="reborn_date_published",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
