# Generated by Django 5.1.9 on 2025-06-27 12:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0002_alter_datatype_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="softwaremethod",
            name="is_implemented_by",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
