# Generated by Django 5.2.6 on 2025-09-16 09:21

import core.infrastructure.models.sql_models
import core.infrastructure.repositories.sql_repos_helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0002_alter_article_research_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="ro_crate",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.infrastructure.models.sql_models.OverwriteStorage(),
                upload_to=core.infrastructure.repositories.sql_repos_helper.articlet_ro_crate_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="dataitem",
            name="source_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.infrastructure.models.sql_models.OverwriteStorage(),
                upload_to=core.infrastructure.models.sql_models.dataitem_source_file_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="figure",
            name="source_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=core.infrastructure.models.sql_models.OverwriteStorage(),
                upload_to=core.infrastructure.models.sql_models.figure_source_image_upload_path_alternative,
            ),
        ),
        migrations.AlterField(
            model_name="implement",
            name="source_code",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.infrastructure.models.sql_models.OverwriteStorage(),
                upload_to=core.infrastructure.models.sql_models.implement_source_code_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="json_ld",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.infrastructure.models.sql_models.OverwriteStorage(),
                upload_to="json_ld_files/",
            ),
        ),
    ]
