# Generated by Django 5.1.9 on 2025-08-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0002_dataitem_statement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataitem",
            name="statement",
        ),
        migrations.AddField(
            model_name="dataitem",
            name="statement_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
