# Generated by Django 5.2.6 on 2025-09-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0002_remove_property_properties__id_5965b6_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constraint",
            name="label",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
