# Generated by Django 5.1.9 on 2025-08-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0003_article_reborn_date_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataitem",
            name="source_file",
            field=models.FileField(blank=True, null=True, upload_to="csv_files/"),
        ),
        migrations.AddField(
            model_name="figure",
            name="source_image",
            field=models.ImageField(blank=True, null=True, upload_to="image_files/"),
        ),
    ]
