# Generated by Django 5.1.9 on 2025-07-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0003_alter_softwaremethod_is_implemented_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataitem",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
    ]
