# Generated by Django 5.1.9 on 2025-08-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0003_remove_dataitem_statement_dataitem_statement_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="figure",
            name="statement_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
