# Generated by Django 5.2.6 on 2025-09-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0003_alter_constraint_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matrix",
            name="label",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="operation",
            name="label",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
