# Generated by Django 5.2.6 on 2025-09-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_alter_matrix_label_alter_operation_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statement",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
