# Generated by Django 5.1.9 on 2025-07-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_alter_dataitem_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="identifier",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="paper_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="reborn_doi",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="json_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="json_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataitem",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataitem",
            name="source_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataitemcomponent",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataitemcomponent",
            name="see_also",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="figure",
            name="source_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="haspart",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="haspart",
            name="type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="implement",
            name="url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="martixsize",
            name="number_columns",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="martixsize",
            name="number_rows",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharedtype",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharedtype",
            name="type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="software",
            name="has_support_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="software",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="software",
            name="version_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="softwarelibrary",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="softwarelibrary",
            name="version_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="softwaremethod",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="mean",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="standard_deviation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
