# Generated by Django 5.1.9 on 2025-08-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_dataitem_source_file_figure_source_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="implement",
            name="source_code",
            field=models.FileField(
                blank=True, null=True, upload_to="source_code_files/"
            ),
        ),
    ]
