# Generated by Django 5.1.9 on 2025-08-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0005_implement_source_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="ro_crate",
            field=models.FileField(blank=True, null=True, upload_to="ro_crate_files/"),
        ),
        migrations.AddField(
            model_name="statement",
            name="json_ld",
            field=models.FileField(blank=True, null=True, upload_to="json_ld_files/"),
        ),
    ]
