# Generated by Django 5.1.9 on 2025-07-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "infrastructure",
            "0005_alter_article_identifier_alter_article_paper_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="datatype",
            name="schema_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_type",
                to="infrastructure.schematype",
            ),
        ),
    ]
