# Generated by Django 5.1.9 on 2025-08-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0006_article_ro_crate_statement_json_ld"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataitem",
            name="source_file",
            field=models.FileField(blank=True, null=True, upload_to="dataset_files/"),
        ),
    ]
