# Generated by Django 5.1.9 on 2025-07-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0006_datatype_schema_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
