# Generated by Django 5.1.9 on 2025-07-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="institution",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Institution"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="orcid_id",
            field=models.CharField(
                blank=True,
                max_length=19,
                null=True,
                unique=True,
                verbose_name="ORCID ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Username"
            ),
        ),
    ]
